FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o /app/main .

FROM alpine:3.20

WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/main /app/main
COPY --from=builder /app/ao /app/ao

ENV RUNTIME_TYPE=test
EXPOSE 8080

CMD ["/app/main"]
